#setopt correct_all

alias man='nocorrect man'
alias mv='nocorrect mv'
alias mysql='nocorrect mysql'
alias mkdir='nocorrect mkdir'
alias gist='nocorrect gist'
alias heroku='nocorrect heroku'
alias ebuild='nocorrect ebuild'
alias hpodder='nocorrect hpodder'
alias sudo='nocorrect sudo'
alias pkill='nocorrect pkill'
alias killall='nocorrect killall'
alias pacman='nocorrect sudo pacman'
alias yaourt='nocorrect yaourt'
